### ISSUE TITLE
No type named 'BackupEngine' in namespace 'rocksdb'

### ISSUE THREAD

**Issue by jerryliurui** [iabudiab/ObjectiveRocks#4] opened 2017-07-13 18:17 UTC
rocksdb::BackupEngine *_backupEngine;

**Comment by jerryliurui** [comment] 2017-07-13 18:38
I'm trying to write a file like RocksDBBackupEngine.mm. But i face the up question like U see.
Please help me. 
Can U tell me how you fix this program when you design this class.
Thank you very much.

**Comment by iabudiab** [comment] 2017-07-14 17:55
@jerryliurui Are you trying to implement this for iOS? If so, then you are out of luck, unless you are willing to invest lots of time.

Some features of `rocksdb` are not available for iOS or in the so called `ROCKSDB_LITE` version. Take a look at the [include guards](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/utilities/backupable_db.h#L13) at the top of the header file.

There are several features that are not included in the `ROCKSDB_LITE` version:

- Column Family Metadata
- Write Batch with Index
- Plain and Cuckoo Table Factories
- Vector, HashSkipList, HashLinkList and HashCuckoo Memtable Rep Factories
- Database Backups
- Database Statistics
- Database Properties
- Thread Status

If the issue is not related to iOS then could you give me more information about the problem? A snippet or a sample project maybe?

**Comment by jerryliurui** [comment] 2017-07-17 08:46
Thank you very much.
Just like you say , i wish to accomplish backup of RocksDB for iOS....
But it looks Time-consuming...
Thanks a lot~
Best wishes for you.

**Comment by iabudiab** [comment] 2017-07-20 19:44
@jerryliurui You're welcome! Let me know if there is anything else I could help you with. Will be glad to help 👍  I'll close this issue then.

**Closed as completed by iabudiab** 2017-07-20 19:44 UTC
Labels: question, needs feedback
